//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Logic.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public Lot()
        {
            this.UserLots = new HashSet<UserLot>();
        }
    
        public int IdLot { get; set; }
        public int IdSection { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal StartPrice { get; set; }
        public decimal Tick { get; set; }
        public decimal CurrentPrice { get; set; }
        public bool Status { get; set; }
        public string Img { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<UserLot> UserLots { get; set; }
    }
}
