//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Logic.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLot
    {
        public StatusLot()
        {
            this.UserLots = new HashSet<UserLot>();
        }
    
        public int Id { get; set; }
        public string NameStatus { get; set; }
    
        public virtual ICollection<UserLot> UserLots { get; set; }
    }
}
