//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Logic.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLot
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdLot { get; set; }
        public int idStatus { get; set; }
    
        public virtual StatusLot StatusLot { get; set; }
        public virtual User User { get; set; }
        public virtual Lot Lot { get; set; }
    }
}
